alias ll='ls -lrt'
alias la='ls -lart'
alias l='ls'
alias dps='docker ps -a'
alias drm='docker remove'
alias vim='nvim'
alias v="nvim"

# For iterm2: Install shell-integration scripts:
# Open iTerm2 and go to iTerm2 > Install Shell Integration.
export HISTFILE=~/.bash_history
shopt -s histappend
export PROMPT_COMMAND="history -a; history -n; $PROMPT_COMMAND"

# fzf & custom script environment variables
export FZF_COMPLETION_TRIGGER='!!'
export HTTPSTAT_SAVE_BODY=false

# iterm2
test -e "${HOME}/.iterm2_shell_integration.bash" && source "${HOME}/.iterm2_shell_integration.bash" || true
export PATH="$PATH:/usr/local/bin/:/opt/homebrew/bin:$PATH"

[ -f ~/.fzf.bash ] && source ~/.fzf.bash
[ -f ~/.ee-completion.bash ] && source ~/.ee-completion.bash
[ -f ~/.bash_aliases ] && source ~/.bash_aliases

source ~/.bash_profile

# Could be put in ~/.profile instead
# node version manager
export NVM_DIR="$([ -z "${XDG_CONFIG_HOME-}" ] && printf %s "${HOME}/.nvm" || printf %s "${XDG_CONFIG_HOME}/nvm")"
[ -s "$NVM_DIR/nvm.sh" ] && \. "$NVM_DIR/nvm.sh" # This loads nvm

# ruby version manager
[[ -s "$HOME/.rvm/scripts/rvm" ]] && source "$HOME/.rvm/scripts/rvm" # Load RVM into a shell session *as a function*
export PATH="$PATH:$HOME/bin:$HOME/.rvm/bin"
